### PR TITLE
Adds support for alternate encodings for ttl records (e.g. bytewise)

### PR DESCRIPTION
**Pull request by deanlandolt**
I tried to be as unobtrusive as possible but I know this is a pretty massive commit. FWIW it should be completely backward-compatible.

Let me know if there's anything you'd like to see changed to get this merged.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
There are some style things that should be adjusted. Other than that I'm +1 on this. Would love to get some input from @rvagg and @mcollina

**Comment by mcollina** [comment]
I think the code is already too complicated for being a single file. How about splitting the encoding stuff in its own file?

**Comment by deanlandolt** [comment]
@mcollina sure -- I'll move it out in the next commit.

**Comment by deanlandolt** [comment]
Just pushed up a new patch that addresses all of @ralphtheninja's comments and moves to using real dates over timestamps. I still need to incorporate @mcollina's suggestion of moving encodings stuff to its own module -- I'm feeling around for a decent API for this, maybe aligning w/ how sublevel handles custom encodings. It would also be nice to respect a provided `sub`'s encoding preferences, but this seems to be a bit less trivial than it should be.

**Comment by juliangruber** [comment]
+1 on moving code to more files, this and the fact that i'm new to the code make it hard to review

**Comment by deanlandolt** [comment]
I moved out the encodings stuff to its own module and fixed formatting per @ralphtheninja's comment. Just let me know if there's anything else.

**Comment by hij1nx** [comment]
+1 for the idea behind this patch (i haven't read the patch, but i would really like this)

**Comment by ralphtheninja** [comment]
I'll go through it today. Would be nice if someone else had some time over as well.

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ level-ttl@3.1.0
```

**Pull request merged**
